server:
  port: 8086

spring:
  application:
    name: CHECKIN-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/checkindb
    username: root
    password: Shinzo@79###
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
