server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: search-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/flights/**
        - id: admin-service
          uri: http://localhost:8083
          predicates:
            - Path=/admin/**
        - id: booking-service
          uri: http://localhost:8084
          predicates:
            - Path=/booking/**
        - id: payment-service
          uri: http://localhost:8085
          predicates:
            - Path=/payment/**
        - id: auth-service
          uri: http://localhost:8088
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
