server:
  port: 8083

spring:
  application:
    name: ADMIN-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/admindb
    username: root
    password: Shinzo@79###
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
